# general
batch_size: 128
input_size: 112
embd_shape: 512
sub_name: 'arc_res50_ccrop'
backbone_type: 'ResNet50' # 'ResNet50', 'MobileNetV2'
head_type: ArcHead # 'ArcHead', 'NormHead'
is_ccrop: True # central-cropping or not

# train
train_dataset: './data/align_face_bin.tfrecord'
binary_img: True
num_classes: 85742
num_samples: 5822653
epochs: 5
base_lr: 0.01
w_decay: !!float 5e-4
save_steps: 1000

# test
test_dataset: 'test_dataset'
pre_trained_model: './models/arc_res50_ccrop'
